#!/bin/bash

ffmpeg -i $1.mp3 -f s16le -ar 48000 -ac 2 pipe:1 | dca > $1.dca
mv $1.mp3 converted/
mv $1.dca sounds/
echo "Add this line to the main function: "
echo "add_track(\"$1\", \"$1.dca\", \"$2\")"
